language: groovy
jdk: oraclejdk8
install:
  - "TERM=dumb ./gradlew sourcesJar jar dist"
before_script:
  - "TERM=dumb ./gradlew dependencyUpdates"
script:
  - "TERM=dumb ./gradlew test"
notifications:
  irc:
    channels:
      - "irc.esper.net#directcode"
    on_success: always
    on_failure: always
  slack: directcode:pmuuQYDJL2WyjBMBReuNwxFw
matrix:
  allow_failures:
    - jdk: oraclejdk7
